// mg/pattern.h -- MusicGen's delayed codebook pattern (audiocraft
// modules/codebooks_patterns.py::DelayedPatternProvider).
//
// EnCodec gives `n_q` codebooks per timestep. MusicGen does not model them in parallel: it
// interleaves them so that codebook q at sequence step s carries timestep `s - 1 - q`. Step
// 0 is entirely special tokens, and the sequence runs `max_delay` steps past the audio so
// the last timestep's deepest codebook has somewhere to live.
//
//   codes                    sequence (S = special token)
//   [[1, 2, 3, 4],           [[S, 1, 2, 3, 4, S, S, S],
//    [1, 2, 3, 4],    ->      [S, S, 1, 2, 3, 4, S, S],
//    [1, 2, 3, 4],            [S, S, S, 1, 2, 3, 4, S],
//    [1, 2, 3, 4]]            [S, S, S, S, 1, 2, 3, 4]]
//
// audiocraft builds this by materializing a layout of coordinate lists and then scatter
// indexes over a flattened tensor. Nothing about it needs to be dynamic for the delays
// MusicGen ships, so it is a closed form here -- but the closed form is exactly the kind of
// thing that is easy to get subtly wrong, so tests/pattern_test.cpp checks it against
// fixtures generated by the real `DelayedPatternProvider`.
//
// Codes are laid out [n_q][T] -- codebook-major, `q * T + t` -- and sequences [n_q][S].
#pragma once

#include <algorithm>
#include <cstdint>
#include <stdexcept>
#include <vector>

namespace ac {

struct DelayPattern {
    std::vector<int> delays;
    int timesteps = 0;

    DelayPattern() = default;
    DelayPattern(std::vector<int> d, int t) : delays(std::move(d)), timesteps(t) {
        if (delays.empty()) throw std::runtime_error("the delay pattern has no codebooks");
        if (timesteps <= 0) throw std::runtime_error("the delay pattern needs a positive length");
        // audiocraft asserts the delays are sorted; the layout construction relies on it and
        // so does first_step_with_timestep.
        if (!std::is_sorted(delays.begin(), delays.end()))
            throw std::runtime_error("delays must be non-decreasing");
        if (delays.front() < 0) throw std::runtime_error("delays must be non-negative");
    }

    int codebooks() const { return (int)delays.size(); }
    int max_delay() const { return delays.back(); }

    // The layout is one empty step followed by `timesteps + max_delay` populated ones.
    int steps() const { return 1 + timesteps + max_delay(); }

    // The timestep codebook `q` carries at sequence step `s`, or -1 when that position
    // holds the special token. Step 0 is empty by construction, and the tail of the
    // sequence runs past the audio for every codebook shallower than the deepest.
    int timestep_at(int q, int s) const {
        if (s <= 0) return -1;
        const int t = s - 1 - delays[(size_t)q];
        return (t >= 0 && t < timesteps) ? t : -1;
    }

    // The first sequence step that carries timestep `t` in any codebook -- where the
    // autoregressive loop starts after a prompt of `t` timesteps. With sorted delays the
    // shallowest codebook gets there first.
    int first_step_with_timestep(int t) const {
        if (t < 0 || t >= timesteps) throw std::runtime_error("timestep is outside the pattern");
        return t + 1 + delays.front();
    }
};

// [n_q][timesteps] -> [n_q][steps]. Positions that carry no timestep get `special`.
//
// `codes` may hold negative values for timesteps that have not been generated yet, which is
// how `LMModel.generate` seeds the sequence: the prompt is written, the rest is -1, and the
// loop fills the -1s in as it goes.
inline std::vector<int32_t> build_pattern_sequence(const DelayPattern& p, const int32_t* codes,
                                                   int32_t special) {
    const int K = p.codebooks(), S = p.steps(), T = p.timesteps;
    std::vector<int32_t> seq((size_t)K * S, special);
    for (int q = 0; q < K; ++q) {
        for (int s = 0; s < S; ++s) {
            const int t = p.timestep_at(q, s);
            if (t >= 0) seq[(size_t)q * S + s] = codes[(size_t)q * T + t];
        }
    }
    return seq;
}

// [n_q][steps] -> [n_q][timesteps]. Timesteps the sequence does not reach get `special`.
inline std::vector<int32_t> revert_pattern_sequence(const DelayPattern& p, const int32_t* seq,
                                                    int32_t special) {
    const int K = p.codebooks(), S = p.steps(), T = p.timesteps;
    std::vector<int32_t> codes((size_t)K * T, special);
    for (int q = 0; q < K; ++q) {
        for (int s = 0; s < S; ++s) {
            const int t = p.timestep_at(q, s);
            if (t >= 0) codes[(size_t)q * T + t] = seq[(size_t)q * S + s];
        }
    }
    return codes;
}

// 1 where a sequence position carries a real timestep, 0 where it is the special token.
//
// `generate` uses this twice per step: to force positions the model should not have spoken
// for back to the special token, and to decide which positions are still unknown and may be
// written. The model never emits the special token itself, so without this the tail of the
// sequence would fill with real codes that revert to nothing.
inline std::vector<uint8_t> pattern_mask(const DelayPattern& p) {
    const int K = p.codebooks(), S = p.steps();
    std::vector<uint8_t> mask((size_t)K * S, 0);
    for (int q = 0; q < K; ++q)
        for (int s = 0; s < S; ++s)
            mask[(size_t)q * S + s] = p.timestep_at(q, s) >= 0 ? 1 : 0;
    return mask;
}

} // namespace ac
